master-chart:
  nameOverride: spring-boot-api
  fullnameOverride: spring-boot-api
  namespace: prd-spring-boot
  appName: spring-boot-api
  application:
    image:
      repository: busybox
      pullPolicy: IfNotPresent
      tag: stable

    replicaCount: 0
    autoscaling:
      enabled: false
      minReplicas: 0
      maxReplicas: 10
  
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  
    livenessProbe:
      httpGet:
        path: /api
        port: http
  
    readinessProbe:
      httpGet:
        path: /api
        port: http
  
    envs:
    - name: JAVA_TOOLS_OPTIONS
      value: --spring.profiles.active=prd
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: spring-boot-api-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: spring-boot-api-secret
          key: password
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: spring-boot-api-secret
          key: apiKey
  
    volumes: 
    - name: spring-boot-config
      configMap:
        name: spring-boot-api-configmap
        
    volumeMounts:
    - name: spring-boot-config
      mountPath: "app/config.json"
      readOnly: true
  
    preStopCommand: wget http://localhost:8080/service/shutdown
  
  
  service:
    type: ClusterIP
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: logs
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: soap
      port: 8082
      protocol: TCP
      targetPort: 8082
  
  ingress:
    enabled: true
    hosts:
      - host: spring-boot-api.prd.net
    paths:
    - serviceName: spring-boot-api-service
      path: /api
      servicePort: 8080
      pathType: ImplementationSpecific
    - serviceName: spring-boot-api-service
      path: /logs
      servicePort: 8081
      pathType: ImplementationSpecific
    - serviceName: spring-boot-api-service
      path: /soap
      servicePort: 8082
      pathType: ImplementationSpecific
  
  
  configmap:
    create: false
    configmapContents: |
      {
          "current_env" : "dev",
          "clusterName" : "dev-global-cluster-0",
          "clusterHost" : "kind"
      }
  
  secretData:
    username: c3ByaW5nLWJvb3QtYXBp
  
  serviceAccount:
    name: spring-boot-api
  
