apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prd-spring-boot
  namespace: argocd
spec:
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  # Current resource whitelist (without Namespace)
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"