apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bartek-babu/demo-spring-boot'
    path: apps
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: app-sets
  syncPolicy:
    automated: {}
